### ISSUE TITLE
Do we have to specify the classpath?

### ISSUE THREAD

**Issue by tszdanger** [CastleLab/COMP5111-Spring2022-Student-Assignments#1]
When using Randoop, do we have to specify the class path?

I change the ins into `java randoop.main.Main gentests --testclass=src.main.java.comp5111.assignment.cut.Subject --time-limit=60 --junit-package-name=src.main.java.comp5111.assignment.cut --junit-output-dir=./src/test/randoop0` and it turn out that doesnt work

**Comment by tszdanger** [comment]
Since I'v already add the jar into the SYS PATH, I dont see any reason to do like this

**Comment by tszdanger** [comment]
Quit strange when doing that on F windows

**Comment by maybeLee** [comment]
Hi, if you are running the randoop on powershell, you should use quotes to wrap the classpath. 
Anyway, I present the example command to run randoop on the PowerShell:
(Suppose you have compiled the CUT: `Subject.java` and save it to `raw-classes`)

PowerShell:
```
java --classpath "lib/*;raw-classes" randoop.main.Main gentests --testclass="comp5111.assignment.cut.Subject" --time-limit=60 --junit-package-name="comp5111.assignment.cut" --junit-output-dir="src/test/randoop0"
```

If you are running on cmd, you may refer to the script example (`./scripts/gen-tests.cmd`) provided in our workshop: https://course.cse.ust.hk/comp5111/assignments_2022S/soot-example.zip
or our tutorial:
```
java -ea -classpath %RANDOOP_JAR%;%TARGET% randoop.main.Main gentests --testclass=comp5111.assignment.cut.Subject --time-limit=60 --junit-package-name=comp5111.assignment.cut --junit-output-dir=%ROOT_DIR%/src/test/randoop0
```
Of course you can add your classpath to the environment variable `CLASSPATH`, anyway, using setting classpath through command line is more convenient.
